spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zom
    username: root                      # Your MySQL username
    password: 9027707502            # Your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true                     # Show SQL queries in console
    hibernate:
      ddl-auto: update                 # Automatically update schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 
        # dialect: org.hibernate.dialect.MySQL8Dialect

   
      
